# Generated by Django 3.2.13 on 2022-05-13 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 18, 31, 22, 593581)),
        ),
    ]
