# Generated by Django 3.2.13 on 2022-05-13 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220513_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 18, 43, 45, 602863)),
        ),
    ]
